<?php
// $Id$

/**
 * @file
 * Adds css to admin them when needed.
 *
 */

 function pncadmin_preprocess_html(&$variables) {
   // Add conditional stylesheets for admin pages on admin theme.
   if (arg(0)=="admin") {
     // reference your current admin theme
     $theme_path = drupal_get_path('theme', 'adminimal_admin_menu');
     // reference your own stylesheet
     drupal_add_css(drupal_get_path('module', 'pncadmin') . '/css/pncadmin.css', array('weight' => CSS_THEME));
   }
 }
