<?php
// $Id$

/**
 * @file
 * Adds a generic block to the build with content of the users choice.
 *
 */

/**
 *   Implements hook_block_info().
 */
function pncgoogleadd_block_info() {
$blocks = array();

$blocks['pncgoogleadd_block'] = array(
    'info' => t('Purencool Google add block'),
    'cache' => DRUPAL_NO_CACHE
    );
 return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pncgoogleadd_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'pncgoogleadd_block':
      $block = array(
        'subject' => t('Google Add Block'),
	'cache' => DRUPAL_NO_CACHE,
        'status' => 1,
        'region' => 'sidebar_first',
        'theme'=>'pncmbtheme',
        'title'=>'<none>',
	'weight'=>'14',
        'content' => _pnc_get_google_block_info(),
      );
      break;
  }
  return $block;
}

/**
 * Adds content to the block
 * @return string
 */
function _pnc_get_google_block_info() {

  $output = '<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
   <!-- Test -->
    <ins class="adsbygoogle"
      style="display:inline-block;width:320px;height:100px"
      data-ad-client="ca-pub-1884809857881094"
      data-ad-slot="9040943560"></ins>
    <script>
   (adsbygoogle = window.adsbygoogle || []).push({});
   </script>';

  return $output;
}
